apiVersion: v1        #creating a pod with mount configmap
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx
    volumeMounts:
    - name: env-prop
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: env-prop
    configMap:
      name: game-env

##############################################################
apiVersion: v1           # creaing a pod with env
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
      envFrom: 
        - configMapRef:
            name: game-env
  volumes:
    - name: config-volume
      configMap:
        name: game-env


---------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-test
data:
  APP_CONFIG: prod
  LOG_LEVEL: info

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx
      env:
        - name: ALLOWED     
          valueFrom:
            configMapKeyRef:
              name: game-env   
              key: allowed 
        - name: LIVENES     
          valueFrom:
            configMapKeyRef:
              name: game-env   
              key: lives
        - name: ENEMIES
          valueFrom:
            configMapKeyRef:
              name: game-env   
              key: enemies
          