apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: logging
  name: logging
spec:
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
      - image: fluentd
        name: fluentd

