apiVersion: batch/v1
kind: Job
metadata:
  name: count123
spec:
  template:
    metadata:
      name: count123
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
         - "bin/bash"
         - "-c"
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"             #use $1; sleep 5 and chcek logs of the pod
      restartPolicy: Never