apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce    # both has to match to the pv
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
  