apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mycontainer
    image: nginx
    volumeMounts:
    - name: mysecret-volume
      mountPath: /etc/mysecret
      readOnly: true
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: suleman-pass
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: suleman-pass
          key: passwd
  volumes:
  - name: mysecret-volume
    secret:
      secretName: suleman-pass
