apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-dep1
  name: my-dep1
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80
  selector:
    app: my-dep1
  type: NodePort
status:
 

